const ShopCategories = [
  { label: 'Clothing & Fashion', value: 'clothing_fashion' },
  { label: 'Electronics', value: 'electronics' },
  { label: 'Beauty & Personal Care', value: 'beauty_personal_care' },
  { label: 'Health & Wellness', value: 'health_wellness' },
  { label: 'Home & Living', value: 'home_living' },
  { label: 'Furniture', value: 'furniture' },
  { label: 'Jewelry & Accessories', value: 'jewelry_accessories' },
  { label: 'Shoes & Footwear', value: 'shoes_footwear' },
  { label: 'Sports & Outdoors', value: 'sports_outdoors' },
  { label: 'Toys & Games', value: 'toys_games' },
  { label: 'Books & Stationery', value: 'books_stationery' },
  { label: 'Food & Beverages', value: 'food_beverages' },
  { label: 'Pet Supplies', value: 'pet_supplies' },
  { label: 'Automotive', value: 'automotive' },
  { label: 'Baby & Kids', value: 'baby_kids' },
  { label: 'Art & Crafts', value: 'art_crafts' },
  { label: 'Gadgets & Accessories', value: 'gadgets_accessories' },
  { label: 'Gifts & Collectibles', value: 'gifts_collectibles' },
  { label: 'Music & Instruments', value: 'music_instruments' },
  { label: 'Office Supplies', value: 'office_supplies' },
  { label: 'Gardening & Plants', value: 'gardening_plants' },
  { label: 'Industrial & Tools', value: 'industrial_tools' },
  { label: 'Travel & Luggage', value: 'travel_luggage' },
  { label: 'Digital Products', value: 'digital_products' },
  { label: 'Handmade Products', value: 'handmade_products' },
  { label: 'Subscription Boxes', value: 'subscription_boxes' },
  { label: 'Luxury Items', value: 'luxury_items' },
  { label: 'Hardware & Construction', value: 'hardware_construction' },
  { label: 'Services', value: 'services' },
  { label: 'Others', value: 'others' },
];

export default ShopCategories;