export const countries = [
  { code: 'AF', name: 'Afghanistan', phone: '+93', flag: '🇦🇫' },
  { code: 'AL', name: 'Albania', phone: '+355', flag: '🇦🇱' },
  { code: 'DZ', name: 'Algeria', phone: '+213', flag: '🇩🇿' },
  { code: 'AS', name: 'American Samoa', phone: '+1684', flag: '🇦🇸' },
  { code: 'AD', name: 'Andorra', phone: '+376', flag: '🇦🇩' },
  { code: 'AO', name: 'Angola', phone: '+244', flag: '🇦🇴' },
  { code: 'AI', name: 'Anguilla', phone: '+1264', flag: '🇦🇮' },
  { code: 'AQ', name: 'Antarctica', phone: '+672', flag: '🇦🇶' },
  { code: 'AG', name: 'Antigua and Barbuda', phone: '+1268', flag: '🇦🇬' },
  { code: 'AR', name: 'Argentina', phone: '+54', flag: '🇦🇷' },
  { code: 'AM', name: 'Armenia', phone: '+374', flag: '🇦🇲' },
  { code: 'AU', name: 'Australia', phone: '+61', flag: '🇦🇺' },
  { code: 'AT', name: 'Austria', phone: '+43', flag: '🇦🇹' },
  { code: 'AZ', name: 'Azerbaijan', phone: '+994', flag: '🇦🇿' },
  { code: 'BH', name: 'Bahrain', phone: '+973', flag: '🇧🇭' },
  { code: 'BD', name: 'Bangladesh', phone: '+880', flag: '🇧🇩' },
  { code: 'BB', name: 'Barbados', phone: '+1246', flag: '🇧🇧' },
  { code: 'BY', name: 'Belarus', phone: '+375', flag: '🇧🇾' },
  { code: 'BE', name: 'Belgium', phone: '+32', flag: '🇧🇪' },
  { code: 'BZ', name: 'Belize', phone: '+501', flag: '🇧🇿' },
  { code: 'BJ', name: 'Benin', phone: '+229', flag: '🇧🇯' },
  { code: 'BT', name: 'Bhutan', phone: '+975', flag: '🇧🇹' },
  { code: 'BO', name: 'Bolivia', phone: '+591', flag: '🇧🇴' },
  { code: 'BA', name: 'Bosnia and Herzegovina', phone: '+387', flag: '🇧🇦' },
  { code: 'BW', name: 'Botswana', phone: '+267', flag: '🇧🇼' },
  { code: 'BR', name: 'Brazil', phone: '+55', flag: '🇧🇷' },
  { code: 'BN', name: 'Brunei Darussalam', phone: '+673', flag: '🇧🇳' },
  { code: 'BG', name: 'Bulgaria', phone: '+359', flag: '🇧🇬' },
  { code: 'BF', name: 'Burkina Faso', phone: '+226', flag: '🇧🇫' },
  { code: 'BI', name: 'Burundi', phone: '+257', flag: '🇧🇮' },
  { code: 'KH', name: 'Cambodia', phone: '+855', flag: '🇰🇭' },
  { code: 'CM', name: 'Cameroon', phone: '+237', flag: '🇨🇲' },
  { code: 'CA', name: 'Canada', phone: '+1', flag: '🇨🇦' },
  { code: 'CV', name: 'Cape Verde', phone: '+238', flag: '🇨🇻' },
  { code: 'CF', name: 'Central African Republic', phone: '+236', flag: '🇨🇫' },
  { code: 'TD', name: 'Chad', phone: '+235', flag: '🇹🇩' },
  { code: 'CL', name: 'Chile', phone: '+56', flag: '🇨🇱' },
  { code: 'CN', name: 'China', phone: '+86', flag: '🇨🇳' },
  { code: 'CO', name: 'Colombia', phone: '+57', flag: '🇨🇴' },
  { code: 'KM', name: 'Comoros', phone: '+269', flag: '🇰🇲' },
  { code: 'CG', name: 'Congo', phone: '+242', flag: '🇨🇬' },
  { code: 'CD', name: 'Congo, Dem. Rep.', phone: '+243', flag: '🇨🇩' },
  { code: 'CR', name: 'Costa Rica', phone: '+506', flag: '🇨🇷' },
  { code: 'HR', name: 'Croatia', phone: '+385', flag: '🇭🇷' },
  { code: 'CU', name: 'Cuba', phone: '+53', flag: '🇨🇺' },
  { code: 'CY', name: 'Cyprus', phone: '+357', flag: '🇨🇾' },
  { code: 'CZ', name: 'Czech Republic', phone: '+420', flag: '🇨🇿' },
  { code: 'DK', name: 'Denmark', phone: '+45', flag: '🇩🇰' },
  { code: 'DJ', name: 'Djibouti', phone: '+253', flag: '🇩🇯' },
  { code: 'DM', name: 'Dominica', phone: '+1767', flag: '🇩🇲' },
  { code: 'DO', name: 'Dominican Republic', phone: '+1', flag: '🇩🇴' },
  { code: 'EC', name: 'Ecuador', phone: '+593', flag: '🇪🇨' },
  { code: 'EG', name: 'Egypt', phone: '+20', flag: '🇪🇬' },
  { code: 'SV', name: 'El Salvador', phone: '+503', flag: '🇸🇻' },
  { code: 'GQ', name: 'Equatorial Guinea', phone: '+240', flag: '🇬🇶' },
  { code: 'ER', name: 'Eritrea', phone: '+291', flag: '🇪🇷' },
  { code: 'EE', name: 'Estonia', phone: '+372', flag: '🇪🇪' },
  { code: 'ET', name: 'Ethiopia', phone: '+251', flag: '🇪🇹' },
  { code: 'FJ', name: 'Fiji', phone: '+679', flag: '🇫🇯' },
  { code: 'FI', name: 'Finland', phone: '+358', flag: '🇫🇮' },
  { code: 'FR', name: 'France', phone: '+33', flag: '🇫🇷' },
  { code: 'DE', name: 'Germany', phone: '+49', flag: '🇩🇪' },
  { code: 'GH', name: 'Ghana', phone: '+233', flag: '🇬🇭' },
  { code: 'GR', name: 'Greece', phone: '+30', flag: '🇬🇷' },
  { code: 'GL', name: 'Greenland', phone: '+299', flag: '🇬🇱' },
  { code: 'GD', name: 'Grenada', phone: '+1473', flag: '🇬🇩' },
  { code: 'GU', name: 'Guam', phone: '+1671', flag: '🇬🇺' },
  { code: 'GT', name: 'Guatemala', phone: '+502', flag: '🇬🇹' },
  { code: 'GY', name: 'Guyana', phone: '+592', flag: '🇬🇾' },
  { code: 'HT', name: 'Haiti', phone: '+509', flag: '🇭🇹' },
  { code: 'HN', name: 'Honduras', phone: '+504', flag: '🇭🇳' },
  { code: 'HK', name: 'Hong Kong', phone: '+852', flag: '🇭🇰' },
  { code: 'HU', name: 'Hungary', phone: '+36', flag: '🇭🇺' },
  { code: 'IS', name: 'Iceland', phone: '+354', flag: '🇮🇸' },
  { code: 'IN', name: 'India', phone: '+91', flag: '🇮🇳' },
  { code: 'ID', name: 'Indonesia', phone: '+62', flag: '🇮🇩' },
  { code: 'IR', name: 'Iran', phone: '+98', flag: '🇮🇷' },
  { code: 'IQ', name: 'Iraq', phone: '+964', flag: '🇮🇶' },
  { code: 'IE', name: 'Ireland', phone: '+353', flag: '🇮🇪' },
  { code: 'IL', name: 'Israel', phone: '+972', flag: '🇮🇱' },
  { code: 'IT', name: 'Italy', phone: '+39', flag: '🇮🇹' },
  { code: 'JM', name: 'Jamaica', phone: '+1876', flag: '🇯🇲' },
  { code: 'JP', name: 'Japan', phone: '+81', flag: '🇯🇵' },
  { code: 'JO', name: 'Jordan', phone: '+962', flag: '🇯🇴' },
  { code: 'KZ', name: 'Kazakhstan', phone: '+7', flag: '🇰🇿' },
  { code: 'KE', name: 'Kenya', phone: '+254', flag: '🇰🇪' },
  { code: 'KR', name: 'South Korea', phone: '+82', flag: '🇰🇷' },
  { code: 'KW', name: 'Kuwait', phone: '+965', flag: '🇰🇼' },
  { code: 'KG', name: 'Kyrgyzstan', phone: '+996', flag: '🇰🇬' },
  { code: 'LA', name: 'Laos', phone: '+856', flag: '🇱🇦' },
  { code: 'LV', name: 'Latvia', phone: '+371', flag: '🇱🇻' },
  { code: 'LB', name: 'Lebanon', phone: '+961', flag: '🇱🇧' },
  { code: 'LS', name: 'Lesotho', phone: '+266', flag: '🇱🇸' },
  { code: 'LR', name: 'Liberia', phone: '+231', flag: '🇱🇷' },
  { code: 'LY', name: 'Libya', phone: '+218', flag: '🇱🇾' },
  { code: 'LT', name: 'Lithuania', phone: '+370', flag: '🇱🇹' },
  { code: 'LU', name: 'Luxembourg', phone: '+352', flag: '🇱🇺' },
  { code: 'MO', name: 'Macao', phone: '+853', flag: '🇲🇴' },
  { code: 'MG', name: 'Madagascar', phone: '+261', flag: '🇲🇬' },
  { code: 'MW', name: 'Malawi', phone: '+265', flag: '🇲🇼' },
  { code: 'MY', name: 'Malaysia', phone: '+60', flag: '🇲🇾' },
  { code: 'MV', name: 'Maldives', phone: '+960', flag: '🇲🇻' },
  { code: 'ML', name: 'Mali', phone: '+223', flag: '🇲🇱' },
  { code: 'MT', name: 'Malta', phone: '+356', flag: '🇲🇹' },
  { code: 'MR', name: 'Mauritania', phone: '+222', flag: '🇲🇷' },
  { code: 'MU', name: 'Mauritius', phone: '+230', flag: '🇲🇺' },
  { code: 'MX', name: 'Mexico', phone: '+52', flag: '🇲🇽' },
  { code: 'MD', name: 'Moldova', phone: '+373', flag: '🇲🇩' },
  { code: 'MC', name: 'Monaco', phone: '+377', flag: '🇲🇨' },
  { code: 'MN', name: 'Mongolia', phone: '+976', flag: '🇲🇳' },
  { code: 'ME', name: 'Montenegro', phone: '+382', flag: '🇲🇪' },
  { code: 'MA', name: 'Morocco', phone: '+212', flag: '🇲🇦' },
  { code: 'MZ', name: 'Mozambique', phone: '+258', flag: '🇲🇿' },
  { code: 'MM', name: 'Myanmar', phone: '+95', flag: '🇲🇲' },
  { code: 'NA', name: 'Namibia', phone: '+264', flag: '🇳🇦' },
  { code: 'NP', name: 'Nepal', phone: '+977', flag: '🇳🇵' },
  { code: 'NL', name: 'Netherlands', phone: '+31', flag: '🇳🇱' },
  { code: 'NZ', name: 'New Zealand', phone: '+64', flag: '🇳🇿' },
  { code: 'NG', name: 'Nigeria', phone: '+234', flag: '🇳🇬' },
  { code: 'NO', name: 'Norway', phone: '+47', flag: '🇳🇴' },
  { code: 'OM', name: 'Oman', phone: '+968', flag: '🇴🇲' },
  { code: 'PK', name: 'Pakistan', phone: '+92', flag: '🇵🇰' },
  { code: 'PS', name: 'Palestine', phone: '+970', flag: '🇵🇸' },
  { code: 'PA', name: 'Panama', phone: '+507', flag: '🇵🇦' },
  { code: 'PG', name: 'Papua New Guinea', phone: '+675', flag: '🇵🇬' },
  { code: 'PY', name: 'Paraguay', phone: '+595', flag: '🇵🇾' },
  { code: 'PE', name: 'Peru', phone: '+51', flag: '🇵🇪' },
  { code: 'PH', name: 'Philippines', phone: '+63', flag: '🇵🇭' },
  { code: 'PL', name: 'Poland', phone: '+48', flag: '🇵🇱' },
  { code: 'PT', name: 'Portugal', phone: '+351', flag: '🇵🇹' },
  { code: 'QA', name: 'Qatar', phone: '+974', flag: '🇶🇦' },
  { code: 'RO', name: 'Romania', phone: '+40', flag: '🇷🇴' },
  { code: 'RU', name: 'Russia', phone: '+7', flag: '🇷🇺' },
  { code: 'RW', name: 'Rwanda', phone: '+250', flag: '🇷🇼' },
  { code: 'SA', name: 'Saudi Arabia', phone: '+966', flag: '🇸🇦' },
  { code: 'SN', name: 'Senegal', phone: '+221', flag: '🇸🇳' },
  { code: 'RS', name: 'Serbia', phone: '+381', flag: '🇷🇸' },
  { code: 'SC', name: 'Seychelles', phone: '+248', flag: '🇸🇨' },
  { code: 'SL', name: 'Sierra Leone', phone: '+232', flag: '🇸🇱' },
  { code: 'SG', name: 'Singapore', phone: '+65', flag: '🇸🇬' },
  { code: 'SK', name: 'Slovakia', phone: '+421', flag: '🇸🇰' },
  { code: 'SI', name: 'Slovenia', phone: '+386', flag: '🇸🇮' },
  { code: 'SO', name: 'Somalia', phone: '+252', flag: '🇸🇴' },
  { code: 'ZA', name: 'South Africa', phone: '+27', flag: '🇿🇦' },
  { code: 'SS', name: 'South Sudan', phone: '+211', flag: '🇸🇸' },
  { code: 'ES', name: 'Spain', phone: '+34', flag: '🇪🇸' },
  { code: 'LK', name: 'Sri Lanka', phone: '+94', flag: '🇱🇰' },
  { code: 'SD', name: 'Sudan', phone: '+249', flag: '🇸🇩' },
  { code: 'SR', name: 'Suriname', phone: '+597', flag: '🇸🇷' },
  { code: 'SZ', name: 'Eswatini', phone: '+268', flag: '🇸🇿' },
  { code: 'SE', name: 'Sweden', phone: '+46', flag: '🇸🇪' },
  { code: 'CH', name: 'Switzerland', phone: '+41', flag: '🇨🇭' },
  { code: 'SY', name: 'Syria', phone: '+963', flag: '🇸🇾' },
  { code: 'TW', name: 'Taiwan', phone: '+886', flag: '🇹🇼' },
  { code: 'TJ', name: 'Tajikistan', phone: '+992', flag: '🇹🇯' },
  { code: 'TZ', name: 'Tanzania', phone: '+255', flag: '🇹🇿' },
  { code: 'TH', name: 'Thailand', phone: '+66', flag: '🇹🇭' },
  { code: 'TL', name: 'Timor-Leste', phone: '+670', flag: '🇹🇱' },
  { code: 'TG', name: 'Togo', phone: '+228', flag: '🇹🇬' },
  { code: 'TT', name: 'Trinidad and Tobago', phone: '+1868', flag: '🇹🇹' },
  { code: 'TN', name: 'Tunisia', phone: '+216', flag: '🇹🇳' },
  { code: 'TR', name: 'Turkey', phone: '+90', flag: '🇹🇷' },
  { code: 'TM', name: 'Turkmenistan', phone: '+993', flag: '🇹🇲' },
  { code: 'UG', name: 'Uganda', phone: '+256', flag: '🇺🇬' },
  { code: 'UA', name: 'Ukraine', phone: '+380', flag: '🇺🇦' },
  { code: 'AE', name: 'United Arab Emirates', phone: '+971', flag: '🇦🇪' },
  { code: 'GB', name: 'United Kingdom', phone: '+44', flag: '🇬🇧' },
  { code: 'US', name: 'United States', phone: '+1', flag: '🇺🇸' },
  { code: 'UY', name: 'Uruguay', phone: '+598', flag: '🇺🇾' },
  { code: 'UZ', name: 'Uzbekistan', phone: '+998', flag: '🇺🇿' },
  { code: 'VE', name: 'Venezuela', phone: '+58', flag: '🇻🇪' },
  { code: 'VN', name: 'Vietnam', phone: '+84', flag: '🇻🇳' },
  { code: 'YE', name: 'Yemen', phone: '+967', flag: '🇾🇪' },
  { code: 'ZM', name: 'Zambia', phone: '+260', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwe', phone: '+263', flag: '🇿🇼' },
];
