const Countries = [
  { code: 'AU', name: 'Australia', phone: '+61', flag: '🇦🇺' },
  { code: 'AT', name: 'Austria', phone: '+43', flag: '🇦🇹' },
  { code: 'BE', name: 'Belgium', phone: '+32', flag: '🇧🇪' },
  { code: 'BR', name: 'Brazil', phone: '+55', flag: '🇧🇷' },
  { code: 'BG', name: 'Bulgaria', phone: '+359', flag: '🇧🇬' },
  { code: 'CA', name: 'Canada', phone: '+1', flag: '🇨🇦' },
  { code: 'HR', name: 'Croatia', phone: '+385', flag: '🇭🇷' },
  { code: 'CY', name: 'Cyprus', phone: '+357', flag: '🇨🇾' },
  { code: 'CZ', name: 'Czech Republic', phone: '+420', flag: '🇨🇿' },
  { code: 'DK', name: 'Denmark', phone: '+45', flag: '🇩🇰' },
  { code: 'EE', name: 'Estonia', phone: '+372', flag: '🇪🇪' },
  { code: 'FI', name: 'Finland', phone: '+358', flag: '🇫🇮' },
  { code: 'FR', name: 'France', phone: '+33', flag: '🇫🇷' },
  { code: 'DE', name: 'Germany', phone: '+49', flag: '🇩🇪' },
  { code: 'GI', name: 'Gibraltar', phone: '+350', flag: '🇬🇮' },
  { code: 'GR', name: 'Greece', phone: '+30', flag: '🇬🇷' },
  { code: 'HK', name: 'Hong Kong', phone: '+852', flag: '🇭🇰' },
  { code: 'HU', name: 'Hungary', phone: '+36', flag: '🇭🇺' },
  { code: 'IN', name: 'India', phone: '+91', flag: '🇮🇳' },
  { code: 'IE', name: 'Ireland', phone: '+353', flag: '🇮🇪' },
  { code: 'IT', name: 'Italy', phone: '+39', flag: '🇮🇹' },
  { code: 'JP', name: 'Japan', phone: '+81', flag: '🇯🇵' },
  { code: 'LV', name: 'Latvia', phone: '+371', flag: '🇱🇻' },
  { code: 'LI', name: 'Liechtenstein', phone: '+423', flag: '🇱🇮' },
  { code: 'LT', name: 'Lithuania', phone: '+370', flag: '🇱🇹' },
  { code: 'LU', name: 'Luxembourg', phone: '+352', flag: '🇱🇺' },
  { code: 'MY', name: 'Malaysia', phone: '+60', flag: '🇲🇾' },
  { code: 'MT', name: 'Malta', phone: '+356', flag: '🇲🇹' },
  { code: 'MX', name: 'Mexico', phone: '+52', flag: '🇲🇽' },
  { code: 'NL', name: 'Netherlands', phone: '+31', flag: '🇳🇱' },
  { code: 'NZ', name: 'New Zealand', phone: '+64', flag: '🇳🇿' },
  { code: 'NO', name: 'Norway', phone: '+47', flag: '🇳🇴' },
  { code: 'PL', name: 'Poland', phone: '+48', flag: '🇵🇱' },
  { code: 'PT', name: 'Portugal', phone: '+351', flag: '🇵🇹' },
  { code: 'RO', name: 'Romania', phone: '+40', flag: '🇷🇴' },
  { code: 'SG', name: 'Singapore', phone: '+65', flag: '🇸🇬' },
  { code: 'SK', name: 'Slovakia', phone: '+421', flag: '🇸🇰' },
  { code: 'SI', name: 'Slovenia', phone: '+386', flag: '🇸🇮' },
  { code: 'ES', name: 'Spain', phone: '+34', flag: '🇪🇸' },
  { code: 'SE', name: 'Sweden', phone: '+46', flag: '🇸🇪' },
  { code: 'CH', name: 'Switzerland', phone: '+41', flag: '🇨🇭' },
  { code: 'TH', name: 'Thailand', phone: '+66', flag: '🇹🇭' },
  { code: 'AE', name: 'United Arab Emirates', phone: '+971', flag: '🇦🇪' },
  { code: 'GB', name: 'United Kingdom', phone: '+44', flag: '🇬🇧' },
  { code: 'US', name: 'United States', phone: '+1', flag: '🇺🇸' },
];

export default Countries;